export const PRODUCT_TYPES = {
  //fetch products
  FETCH_PRODUCTS_START:'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS:'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILED:'FETCH_PRODUCTS_FAILED',

  //filter types
  FILTER_BY_MATERIAL:'FILTER_BY_MATERIAL',
  CLEAR_FILTER:'CLEAR_FILTER',

  //stock updates
  ADD_TO_STOCK:'ADD_TO_STOCK',
  RESTORE_STOCK:'RESTORE_STOCK',
  REDUCE_STOCK:'REDUCE_STOCK'

}
